#ifndef _DT_BINDINGS_QCOM_PHY_USB_HS_28NM_H_
#define _DT_BINDINGS_QCOM_PHY_USB_HS_28NM_H_

/* PHY PLLPTUNE bit values (4x to 11.5x) */
#define PLLPTUNE_4X_VALUE	0x0
#define PLLPTUNE_4P5X_VALUE	0x1
#define PLLPTUNE_5X_VALUE	0x2
#define PLLPTUNE_5P5X_VALUE	0x3
#define PLLPTUNE_6X_VALUE	0x4
#define PLLPTUNE_6P5X_VALUE	0x5
#define PLLPTUNE_7X_VALUE	0x6
#define PLLPTUNE_7P5X_VALUE	0x7
#define PLLPTUNE_8X_VALUE	0x8
#define PLLPTUNE_8P5X_VALUE	0x9
#define PLLPTUNE_9X_VALUE	0xA
#define PLLPTUNE_9P5X_VALUE	0xB
#define PLLPTUNE_10X_VALUE	0xC
#define PLLPTUNE_10P5X_VALUE	0xD
#define PLLPTUNE_11X_VALUE	0xE
#define PLLPTUNE_11P5X_VALUE	0xF

/* PHY PLLITUNE bit values (4x to 1x) */

#define PLLITUNE_1X_VALUE 0x0
#define PLLITUNE_2X_VALUE 0x1
#define PLLITUNE_3X_VALUE 0x2
#define PLLITUNE_4X_VALUE 0x3

/* VREG1P8 BYPASS values */
#define BYPASS_ACTIVE		0x1
#define BYPASS_DISABLED	0x2

#endif
